// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_signup from "./routes/api/auth/signup.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $download from "./routes/download.tsx";
import * as $encrypt_decrypt from "./routes/encrypt-decrypt.tsx";
import * as $files_deleteExpiredFiles from "./routes/files/deleteExpiredFiles.ts";
import * as $files_download from "./routes/files/download.ts";
import * as $files_upload from "./routes/files/upload.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $upload from "./routes/upload.tsx";
import * as $ClientEventHandler from "./islands/ClientEventHandler.tsx";
import * as $CopyLinkButton from "./islands/CopyLinkButton.tsx";
import * as $DecryptForm from "./islands/DecryptForm.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $SignupForm from "./islands/SignupForm.tsx";
import * as $UploadForm from "./islands/UploadForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/signup.ts": $api_auth_signup,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/download.tsx": $download,
    "./routes/encrypt-decrypt.tsx": $encrypt_decrypt,
    "./routes/files/deleteExpiredFiles.ts": $files_deleteExpiredFiles,
    "./routes/files/download.ts": $files_download,
    "./routes/files/upload.ts": $files_upload,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/signup.tsx": $signup,
    "./routes/upload.tsx": $upload,
  },
  islands: {
    "./islands/ClientEventHandler.tsx": $ClientEventHandler,
    "./islands/CopyLinkButton.tsx": $CopyLinkButton,
    "./islands/DecryptForm.tsx": $DecryptForm,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/SignupForm.tsx": $SignupForm,
    "./islands/UploadForm.tsx": $UploadForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
